version: '3.8'
services:
  php-apache-environment:
    image: php:8.2-apache
    container_name: checako
    build:
      context: ./
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html/
    ports:
      - '${APP_PORT}:80'
  db:
    #image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    expose:
      - ${DB_PORT}
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - '${APP_PHPMYADMIN_PORT}:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
volumes:
  db_data:
